// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "alpha male",
            "url": "https://github.com/L1mus",
            "email": "limustadji@gmail.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/movies": {
            "get": {
                "description": "Mengambil daftar semua film dengan support searching, filtering, dan pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get Admin List Movies",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Halaman aktif (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Jumlah data per halaman (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter Bulan",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter Tahun",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sukses mengambil list film",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.AdminResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminMovieListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Query parameter tidak valid",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    }
                }
            },
            "post": {
                "description": "Menambahkan data film baru beserta file poster dan otomatisasi jadwal tayang",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Add New Movie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Judul Film",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File Gambar Poster Film",
                        "name": "poster",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Rilis (Format: YYYY-MM-DD)",
                        "name": "release_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Durasi Jam",
                        "name": "duration_hour",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Durasi Menit",
                        "name": "duration_minute",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sinopsis",
                        "name": "synopsis",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Genre",
                        "name": "genre_ids",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Cast",
                        "name": "cast_ids",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Sutradara",
                        "name": "director_ids",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Kota/Lokasi Bioskop",
                        "name": "location_ids",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Array Tanggal (YYYY-MM-DD)",
                        "name": "dates",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Array Jam Tayang (HH:MM)",
                        "name": "times",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Sukses menambahkan film baru",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Payload input atau file tidak valid",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    }
                }
            }
        },
        "/admin/movies/{id}": {
            "get": {
                "description": "Mengambil data lengkap satu film berdasarkan ID, termasuk semua relasi (genre, cast, director, location, dates, times). Digunakan untuk mengisi form edit movie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get Movie Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Film",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sukses mengambil detail film",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.AdminResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminMovieDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "ID tidak valid",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    },
                    "404": {
                        "description": "Film tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Mengubah data film. Biarkan input kosong jika tidak ingin mengubah data spesifik.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Edit Movie",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Film yang ingin diedit",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Judul Film Baru",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File Gambar Poster Baru",
                        "name": "poster",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Rilis Baru (YYYY-MM-DD)",
                        "name": "release_date",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Durasi Jam Baru",
                        "name": "duration_hour",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Durasi Menit Baru",
                        "name": "duration_minute",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Sinopsis Baru",
                        "name": "synopsis",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Genre Baru",
                        "name": "genre_ids",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Cast Baru",
                        "name": "cast_ids",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Sutradara Baru",
                        "name": "director_ids",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "Array ID Lokasi Baru",
                        "name": "location_ids",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Array Tanggal Baru (YYYY-MM-DD)",
                        "name": "dates",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Array Waktu Baru (HH:MM)",
                        "name": "times",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sukses mengubah data film",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Payload input tidak valid",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    },
                    "404": {
                        "description": "Film tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminResponseError"
                        }
                    }
                }
            }
        },
        "/admin/sales-chart": {
            "get": {
                "tags": [
                    "Admin"
                ],
                "summary": "Get Revenue Sales Chart Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter Judul Film",
                        "name": "movie_name",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "weekly",
                            "monthly"
                        ],
                        "type": "string",
                        "description": "Filter rentang waktu",
                        "name": "filter_by",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.SalesChartResponse"
                            }
                        }
                    }
                }
            }
        },
        "/admin/ticket-sales": {
            "get": {
                "tags": [
                    "Admin"
                ],
                "summary": "Get Ticket Sales Data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter ID Genre",
                        "name": "genre_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter ID Lokasi",
                        "name": "location_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TicketSalesResponse"
                            }
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Authenticate user using email and password to obtain a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login Successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Incorrect email or password",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "403": {
                        "description": "Account not activated (ACCOUNT_NOT_ACTIVATED)",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/auth/check-email": {
            "post": {
                "description": "Request an OTP to reset user password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Forgot Password",
                "parameters": [
                    {
                        "description": "Email Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reset password OTP sent to email",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/auth/check-email/verify-otp": {
            "post": {
                "description": "Verify the OTP sent for password reset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify Reset OTP",
                "parameters": [
                    {
                        "description": "OTP Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyResetOTPReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP verified successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid input data or Invalid/Expired OTP",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/auth/check-email/verify-otp/reset": {
            "post": {
                "description": "Set a new password after successful OTP verification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Reset Password",
                "parameters": [
                    {
                        "description": "New Password Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password has been reset successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid input data, Password Mismatch, or Session Expired",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Invalidate current JWT token by adding it to Redis blacklist",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout User",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized or token not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user and send an OTP to their email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "Register Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Registration Successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "409": {
                        "description": "Email is already registered",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/auth/register/activate": {
            "post": {
                "description": "Verify OTP to activate the user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Activate Account",
                "parameters": [
                    {
                        "description": "Activation Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ActivationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account activated successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid input or Invalid/expired OTP",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/auth/register/resend-otp": {
            "post": {
                "description": "Resend activation OTP to the user's email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Resend OTP",
                "parameters": [
                    {
                        "description": "Email Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP has been resent successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "422": {
                        "description": "Account is already activated",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Failed to resend OTP",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/movies": {
            "get": {
                "description": "fetch all movie data to be displayed on the main page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Get All movies",
                "responses": {
                    "200": {
                        "description": "Success to get data",
                        "schema": {
                            "$ref": "#/definitions/dto.MoviePaginationResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get data",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/movies/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the Movie detail data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Get Movie Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Movie ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MovieDetailResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/movies/:id/showtime": {
            "get": {
                "description": "Get the Showtime data filtered result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Get Showtime Filter",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Movie ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload filter showtime",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ShowtimeFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ShowtimeFilterResponse"
                        }
                    },
                    "400": {
                        "description": "bad request\" \"must be filled",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/movies/{id}/showtimes": {
            "get": {
                "description": "Fetch schedule and cinema details by movie ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Get Movie Showtime Details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Movie ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ShowtimeDetailResponse"
                            }
                        }
                    }
                }
            }
        },
        "/order/booking": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new ticket reservation for selected cinema seats.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Reserve Seats and Create Booking",
                "parameters": [
                    {
                        "description": "Payload containing showtime ID and selected seat IDs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Booking successfully created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateBookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid JSON request payload",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Authentication required",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable - Selected seats are already sold or unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/order/seats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve the seating plan and availability status (Available/Sold) for a specific showtime.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get Cinema Seats Layout",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Showtime Identifier ID",
                        "name": "showtime_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved seating layout data",
                        "schema": {
                            "$ref": "#/definitions/dto.SeatPageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid query parameter",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Valid authentication token required",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/transactions/checkout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Triggers a direct backend-to-backend API request to DOKU Core Sandbox System to simulate a payment invoice creation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DOKU Integration"
                ],
                "summary": "Simulate DOKU Sandbox Checkout Invoice",
                "responses": {
                    "200": {
                        "description": "Successfully received simulated checkout payload from DOKU Core",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Failed communicating with external payment gateway API",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transactions/confirm": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Verify and process transaction clearance (simulates payment settlement).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Simulate/Confirm Payment Complete",
                "parameters": [
                    {
                        "description": "Payload containing transaction ID and booking ID to be confirmed",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConfirmPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment settlement verified and confirmed successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.TicketResultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable - The transaction has already been paid",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/transactions/doku-callback": {
            "post": {
                "description": "Automated HTTP callback listener endpoint designed to receive status notification updates directly pushed by DOKU gateway systems.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DOKU Integration"
                ],
                "summary": "DOKU Webhook Notification Handler Listener",
                "parameters": [
                    {
                        "description": "Raw payload notification structure sent from DOKU",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns status verification token acknowledgement back to DOKU",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid payload structure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/transactions/payment/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve checkout summary details (ticket quantity, seats, total price, user profile) and available payment options.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Payment Page Information",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved payment information summary",
                        "schema": {
                            "$ref": "#/definitions/dto.PaymentPageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Login session expired or token invalid",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "404": {
                        "description": "Not Found - Booking record not found or does not belong to user",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/transactions/qr/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Generates and serves a raw binary PNG QR code image linked to the transaction for entry scanning verification.",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Generate Ticket QR Code Image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns raw binary PNG image of the QR Code",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Failed to generate QR code image output",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/transactions/result/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Fetch the finalized digital ticket receipt details after a successful transaction payment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Digital Ticket Invoice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved final digital ticket information",
                        "schema": {
                            "$ref": "#/definitions/dto.TicketResultResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/transactions/submit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Process the chosen payment method to initiate a transaction and generate payment details (e.g., Virtual Account).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Submit Selected Payment Method",
                "parameters": [
                    {
                        "description": "Payload containing booking ID and selected payment method ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SubmitPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment method submitted successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionModalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Missing or invalid JSON body parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Access denied, this booking does not belong to the authenticated user",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/users/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get list of Order History for logged-in User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get User Order History",
                "responses": {
                    "200": {
                        "description": "Get Order History Succesfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.OrderHistoryRes"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Token not exist / Format token invalid",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/users/history/{id}/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get detailed information for specific order history by user logged-in",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get Detail Information",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Detail Information User Succesfully",
                        "schema": {
                            "$ref": "#/definitions/dto.DetailInformationRes"
                        }
                    },
                    "400": {
                        "description": "Invalid Booking Id Format",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Token not exist / Format token invalid",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        },
        "/users/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the profile data of the logged in user based on the jwt token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get User Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Token not exist",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update user data profile",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update First Name",
                        "name": "first_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Update Last Name",
                        "name": "last_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Update Phone Number",
                        "name": "phone",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Update New Password",
                        "name": "new_password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Confirm New Password",
                        "name": "confirm_password",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Update Photo Profile",
                        "name": "photo",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Profile Succesfully",
                        "schema": {
                            "$ref": "#/definitions/dto.UserUpdateProfileRes"
                        }
                    },
                    "400": {
                        "description": "Invalid Input Data",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Token not exist / Format token invalid",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "422": {
                        "description": "File Too Large / Invalid File Format",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Failed to Update Profile / Failed to Save Image",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ActivationRequest": {
            "type": "object",
            "required": [
                "email",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                }
            }
        },
        "dto.AdminMovieDetailResponse": {
            "type": "object",
            "properties": {
                "cast_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "director_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "duration": {
                    "type": "string"
                },
                "genre_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "location_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "poster": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "times": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.AdminMovieListDTO": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "genres": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "poster": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.AdminMovieListResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AdminMovieListDTO"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "dto.AdminResponseError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Error message detail"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "dto.AdminResponseSuccess": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operation successful"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "dto.CastDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.ConfirmPaymentRequest": {
            "type": "object",
            "required": [
                "booking_id",
                "transaction_id"
            ],
            "properties": {
                "booking_id": {
                    "type": "integer",
                    "example": 1024
                },
                "transaction_id": {
                    "type": "integer",
                    "example": 5001
                }
            }
        },
        "dto.CreateBookingRequest": {
            "type": "object"
        },
        "dto.CreateBookingResponse": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "integer",
                    "example": 1024
                }
            }
        },
        "dto.DetailInformationRes": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "movie_title": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string"
                },
                "qr_code": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "seats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "showtime_date": {
                    "type": "string"
                },
                "showtime_time": {
                    "type": "string"
                },
                "ticket_status": {
                    "type": "string"
                },
                "total_price": {
                    "type": "integer"
                },
                "virtua_account": {
                    "type": "integer"
                }
            }
        },
        "dto.ForgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.GenreDTO": {
            "type": "object",
            "properties": {
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.LocationDTO": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Jakarta"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserDetails"
                }
            }
        },
        "dto.MovieDetailResponse": {
            "type": "object",
            "properties": {
                "casts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CastDTO"
                    }
                },
                "category": {
                    "type": "string",
                    "example": "13+"
                },
                "directors": {
                    "type": "string",
                    "example": "Christopher Nolan"
                },
                "duration": {
                    "type": "string",
                    "example": "2:49:00"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GenreDTO"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "poster": {
                    "type": "string",
                    "example": " https://storage.tickitz.id/posters/interstellar_reborn.jpg"
                },
                "release_date": {
                    "type": "string",
                    "example": "2025-03-15"
                },
                "synopsis": {
                    "type": "string",
                    "example": "Seorang astronot nekat melintasi lubang cacing demi menyelamatkan umat manusia dari kehancuran bumi yang semakin tak layak huni. Perjalanan melintasi ruang dan waktu membawa konsekuensi yang tak pernah ia bayangkan sebelumnya."
                },
                "title": {
                    "type": "string",
                    "example": "Interstellar Reborn"
                }
            }
        },
        "dto.MoviePaginationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MovieResponse"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/dto.PaginationMeta"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.MovieResponse": {
            "type": "object",
            "properties": {
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GenreDTO"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "poster": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.OrderHistoryRes": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "integer"
                },
                "cinema_logo": {
                    "type": "string"
                },
                "cinema_name": {
                    "type": "string"
                },
                "movie_title": {
                    "type": "string"
                },
                "showtime": {
                    "type": "string"
                },
                "status_paid": {
                    "type": "string"
                },
                "status_ticket": {
                    "type": "string"
                }
            }
        },
        "dto.PaginationMeta": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "dto.PaymentMethodDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 2
                },
                "logo": {
                    "type": "string",
                    "example": "/img/pm/DANA.png"
                },
                "name": {
                    "type": "string",
                    "example": "DANA"
                }
            }
        },
        "dto.PaymentPageResponse": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "integer",
                    "example": 1024
                },
                "cinema_name": {
                    "type": "string",
                    "example": "CGV Grand Indonesia"
                },
                "email": {
                    "type": "string",
                    "example": "ali.mustadji@example.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "Ali Mustadji"
                },
                "movie_title": {
                    "type": "string",
                    "example": "Interstellar Reborn"
                },
                "payment_methods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PaymentMethodDTO"
                    }
                },
                "phone": {
                    "type": "string",
                    "example": "081234567890"
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                },
                "seat_labels": {
                    "type": "string",
                    "example": "C7, C8"
                },
                "show_date": {
                    "type": "string",
                    "example": "2026-06-15T00:00:00Z"
                },
                "show_time": {
                    "type": "string",
                    "example": "18:30"
                },
                "total_price": {
                    "type": "integer",
                    "example": 100000
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "agree_terms",
                "email",
                "password"
            ],
            "properties": {
                "agree_terms": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.ResendOTPRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordReq": {
            "type": "object",
            "required": [
                "email",
                "new_password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "dto.ResponseError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal server error/bad request"
                },
                "message": {
                    "type": "string",
                    "example": "Failed get data/internal server error"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "dto.ResponseSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Welcome, John doe"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "dto.SalesChartResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "total_revenue": {
                    "type": "number"
                }
            }
        },
        "dto.SeatDTO": {
            "type": "object",
            "required": [
                "seat_status"
            ],
            "properties": {
                "row": {
                    "type": "string",
                    "example": "C"
                },
                "seat_id": {
                    "type": "integer",
                    "example": 145
                },
                "seat_number": {
                    "type": "integer",
                    "example": 7
                },
                "seat_status": {
                    "type": "string",
                    "enum": [
                        "available",
                        "sold"
                    ],
                    "example": "available"
                },
                "seat_type": {
                    "type": "string",
                    "example": "Regular"
                }
            }
        },
        "dto.SeatPageResponse": {
            "type": "object",
            "properties": {
                "seats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SeatDTO"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/dto.SummaryMovieDTO"
                }
            }
        },
        "dto.ShowtimeDetailResponse": {
            "type": "object",
            "properties": {
                "cinema_id": {
                    "type": "integer"
                },
                "cinema_logo": {
                    "type": "string"
                },
                "cinema_name": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "movie_poster": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "showtime_id": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "dto.ShowtimeFilterRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Jakarta"
                },
                "date": {
                    "type": "string",
                    "example": "2025-06-10T15:04:05Z"
                },
                "show_time": {
                    "type": "string",
                    "example": "hh:mm:ss"
                }
            }
        },
        "dto.ShowtimeFilterResponse": {
            "type": "object",
            "properties": {
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LocationDTO"
                    }
                },
                "showtime": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ShowtimeItemDTO"
                    }
                }
            }
        },
        "dto.ShowtimeItemDTO": {
            "type": "object",
            "properties": {
                "cinema_id": {
                    "type": "integer",
                    "example": 1
                },
                "cinema_logo": {
                    "type": "string",
                    "example": " https://storage.tickitz.id/cinema/ebvid.png"
                },
                "cinema_name": {
                    "type": "string",
                    "example": "ebv.id Grand Indonesia"
                },
                "show_date": {
                    "type": "string",
                    "example": "2025-06-10"
                },
                "show_time": {
                    "type": "string",
                    "example": "13:30:00"
                },
                "showtime_id": {
                    "type": "integer",
                    "example": 2
                },
                "ticket_price": {
                    "type": "integer",
                    "example": 75000
                }
            }
        },
        "dto.SubmitPaymentRequest": {
            "type": "object",
            "required": [
                "booking_id",
                "payment_method_id"
            ],
            "properties": {
                "booking_id": {
                    "type": "integer",
                    "example": 56
                },
                "payment_method_id": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "dto.SummaryMovieDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "13+"
                },
                "cinema_logo": {
                    "type": "string",
                    "example": "https://storage.tickitz.id/cinema/cgv.png"
                },
                "cinema_name": {
                    "type": "string",
                    "example": "CGV Grand Indonesia"
                },
                "movie_poster": {
                    "type": "string",
                    "example": "https://storage.tickitz.id/posters/interstellar_reborn.jpg"
                },
                "movie_title": {
                    "type": "string",
                    "example": "Interstellar Reborn"
                },
                "show_date": {
                    "type": "string",
                    "example": "2026-06-15T00:00:00Z"
                },
                "show_time": {
                    "type": "string",
                    "example": "18:30"
                },
                "ticket_price": {
                    "type": "integer",
                    "example": 50000
                }
            }
        },
        "dto.TicketResultResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "13+"
                },
                "movie_title": {
                    "type": "string",
                    "example": "Interstellar Reborn"
                },
                "payment_status": {
                    "type": "string",
                    "example": "PAID"
                },
                "qr_code": {
                    "type": "string",
                    "example": "TICKITZ-TX-5001-SECURE-STRING"
                },
                "seat_labels": {
                    "type": "string",
                    "example": "C7, C8"
                },
                "show_date": {
                    "type": "string",
                    "example": "2026-06-15T00:00:00Z"
                },
                "show_time": {
                    "type": "string",
                    "example": "18:30"
                },
                "ticket_count": {
                    "type": "integer",
                    "example": 2
                },
                "total_price": {
                    "type": "integer",
                    "example": 100000
                }
            }
        },
        "dto.TicketSalesResponse": {
            "type": "object",
            "properties": {
                "movie_title": {
                    "type": "string"
                },
                "total_sold": {
                    "type": "integer"
                }
            }
        },
        "dto.TransactionModalResponse": {
            "type": "object",
            "properties": {
                "payment_deadline": {
                    "type": "string",
                    "example": "2026-06-13T19:47:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "PENDING"
                },
                "total_price": {
                    "type": "integer",
                    "example": 100000
                },
                "transaction_id": {
                    "type": "integer",
                    "example": 5001
                },
                "virtual_rek": {
                    "type": "integer",
                    "example": 8856001234567890
                }
            }
        },
        "dto.UserDetails": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.UserProfileResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "point": {
                    "type": "integer"
                }
            }
        },
        "dto.UserUpdateProfileRes": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyResetOTPReq": {
            "type": "object",
            "required": [
                "email",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Bearer token used for authorization",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Movie API",
	Description:      "This is a backend project for a web application called E-wallet.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
